name: Generate SBOM as Attestation

on:
  workflow_dispatch:
    inputs:
      cosignVersion:
        description: 'Cosign Version to use'
        required: true
        default: 'v2.0.0'
        type: string
      sbomFormat:
        description: 'Which sbom format to create'
        type: choice
        options:
        - spdx
        - spdx-json
        - cyclonedx
        - cyclonedx-json
      sbomPredicateType:
        description: 'Which SBOM predicateType to use'
        type: choice
        options:
        - https://cyclonedx.org/schema
        - https://cyclonedx.org/bom
        - https://spdx.dev/Document
      vulnOutputFormat:
        type: choice
        description: 'Which vuln output format to use'
        options:
        - 'json'
        - 'sarif'
      vulnPredicate:
        type: choice
        description: 'Which vuln predicateType to use'
        options:
        - 'https://cosign.sigstore.dev/attestation/vuln/v1'
        - 'cosign.sigstore.dev/attestation/vuln/v1'


permissions:
  contents: read
  packages: write
  id-token: write

defaults:
  run:
    shell: bash

jobs:
  create-image-and-attestations:
    name: Create
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - uses: actions/checkout@v2
      - uses: ko-build/setup-ko@v0.6
      - uses: sigstore/cosign-installer@main
        with:
          cosign-release: ${{ inputs.cosignVersion }}
      - name: Create sample image
        run: |
          TIMESTAMP=$(date +%s)
          pushd $(mktemp -d)
          go mod init example.com/demo
          cat <<EOF > main.go
          package main
          import "fmt"
          func main() {
            fmt.Println("hello world: ${TIMESTAMP}")
          }
          EOF
          image=`ko publish -B example.com/demo`
          echo "image=$image" >> $GITHUB_ENV
          echo Created image $image
          popd
      - name: Sign the image
        run: |
          cosign sign --yes ${{ env.image }}
      - name: Create SBOM with syft
        uses: anchore/sbom-action@v0
        with:
          output-file: sbom.out
          image: ${{ env.image }}
          format: ${{ inputs.sbomFormat }}
      - name: Create an SBOM attestation
        run: |
          cosign attest --yes --predicate sbom.out --type ${{ inputs.sbomPredicateType }} ${{ env.image }}
      - name: Scan SBOM
        id: scan
        uses: anchore/scan-action@v3
        with:
          sbom: sbom.out
          severity-cutoff: negligible
          output-format: ${{ inputs.vulnOutputFormat }}
      - name: Create vuln attestation from JSON
        if: ${{ inputs.vulnOutputFormat == 'json' }}
        run: |
          cosign attest --yes --predicate ${{ steps.scan.outputs.json }} --type ${{ inputs.vulPredicateType }} ${{ env.image }}
      - name: Create vuln attestation for Sarif
        if: ${{ inputs.vulnOutputFormat == 'sarif' }}
        run: |
          cosign attest --yes --predicate ${{ steps.scan.outputs.sarif }} --type ${{ inputs.vulPredicateType }} ${{ env.image }}
      - name: Dump the output
        run: |
          echo "Image: ${{ env.image }}"

